package net.thesmallthings.hellcraft.hazard;

import com.mojang.math.Transformation;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Display;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import net.thesmallthings.hellcraft.HellcraftMod;
import net.thesmallthings.hellcraft.config.HellConfig;
import net.thesmallthings.hellcraft.mixin.DisplayAccess;
import org.jetbrains.annotations.Nullable;
import org.joml.Quaternionf;
import org.joml.Vector3f;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

/**
 * A boss's own look (Lucifer and the circle guardians). The real mob is made invisible and an
 * item_display entity showing a model from the Hellcraft resource pack follows it every tick, turning
 * to face whoever it is fighting. The models are in assets/hellcraft/models/item/*.json (generated by
 * tools/gen_models.py): 2 blocks tall, feet at the bottom, face toward -Z.
 * <p>
 * The model is animated as a whole through the display's transformation, which the client interpolates
 * between updates: it grows out of the ground when it appears, breathes while idle, bobs and leans while
 * it walks, rears back before an attack (WINDUP) and lunges into it (STRIKE), squashes into a slam (SLAM),
 * swells in a roar (ROAR), shudders and flashes red when hurt, and topples and sinks when it dies.
 * (Item displays draw their item turned half round, so in the transformation the model's front is +Z.)
 */
public final class BossModel {
	private static final float MODEL_HEIGHT = 2.0f;
	private static final float MAX_TURN = 12.0f;
	private static final String DYING_TAG = "hellcraft_dying_model";
	private static final int SPAWN_TICKS = 20;
	private static final int DEATH_TICKS = 34;
	private static final int HURT_TICKS = 6;
	private static final int HURT_GLOW = 0xFF2A2A;

	public enum Pose {
		IDLE(0), WINDUP(16), STRIKE(8), SLAM(10), ROAR(30);

		final int length;

		Pose(int length) {
			this.length = length;
		}
	}

	/** One model's animation state. */
	private static final class Anim {
		final float scale;
		int age;
		Pose pose = Pose.IDLE;
		int poseTick;
		@Nullable
		Pose queued;
		int hurt;
		int spawn = SPAWN_TICKS;
		int dying = -1;
		@Nullable
		Vec3 last;
		float moving;

		Anim(float scale) {
			this.scale = scale;
		}
	}

	private final ServerLevel level;
	/** Every display carries this tag (and the owner's, so the boss's own leftovers sweeps find it too). */
	private final String modelTag;
	private final String ownerTag;
	/** Where to look for leftover displays when clearing. */
	private final Vec3 home;
	/** boss UUID -> display UUID */
	private final Map<UUID, UUID> displays = new HashMap<>();
	private final Map<UUID, Float> yaws = new HashMap<>();
	/** boss UUID -> extra turn (degrees) so that another side of the model faces the target */
	private final Map<UUID, Float> faceTurns = new HashMap<>();
	/** boss UUID -> a display that was summoned but not found yet */
	private final Map<UUID, Pending> pending = new HashMap<>();
	/** boss UUID -> its model's animation */
	private final Map<UUID, Anim> anims = new HashMap<>();

	/** Models of dead bosses playing their fall, after their fight has let go of them. */
	private static final List<Falling> FALLING = new ArrayList<>();

	private record Falling(ServerLevel level, UUID display, Anim anim) {
	}

	public BossModel(ServerLevel level, String modelTag, String ownerTag, Vec3 home) {
		this.level = level;
		this.modelTag = modelTag;
		this.ownerTag = ownerTag;
		this.home = home;
	}

	/** A falling model left over from a restart has nobody to finish its fall: it goes. */
	public static void register() {
		ServerEntityEvents.ENTITY_LOAD.register((entity, level) -> {
			if (entity.entityTags().contains(DYING_TAG) && FALLING.stream().noneMatch(f -> f.display().equals(entity.getUUID()))) {
				entity.discard();
			}
		});
	}

	/** Plays the falls of dead bosses' models (every tick). */
	public static void tickFalling(MinecraftServer server) {
		for (Iterator<Falling> it = FALLING.iterator(); it.hasNext(); ) {
			Falling f = it.next();
			Entity display = f.level().getEntity(f.display());
			if (display == null) {
				it.remove();
				continue;
			}
			Anim a = f.anim();
			a.dying++;
			if (a.dying >= DEATH_TICKS) {
				display.discard();
				it.remove();
			} else if (a.dying % 2 == 0) {
				apply(display, a, 3);
			}
		}
	}

	/** Hides the boss and gives it the named model, scaled so its height matches `height` blocks. */
	public void attach(LivingEntity boss, String model, float height) {
		if (!HellConfig.get().luciferModels) {
			return;
		}
		boss.setInvisible(true);
		if (boss instanceof Mob mob) {
			// held items and armour would float around the invisible body
			for (EquipmentSlot slot : EquipmentSlot.values()) {
				mob.setItemSlot(slot, ItemStack.EMPTY);
			}
		}
		float scale = height / MODEL_HEIGHT;
		String marker = "hellcraft_model_" + boss.getUUID();
		// it starts tiny, sunk to its feet, and grows out of the ground once it is found (see animate)
		float seed = scale * 0.05f;
		String command = String.format(Locale.ROOT,
				"summon minecraft:item_display %.3f %.3f %.3f {Tags:[\"%s\",\"%s\",\"%s\"],"
						+ "item:{id:\"minecraft:stick\",count:1,components:{\"minecraft:item_model\":\"hellcraft:%s\"}},"
						+ "item_display:\"none\",billboard:\"fixed\",teleport_duration:2,view_range:4.0f,brightness:{sky:15,block:12},"
						+ "transformation:{translation:[0.0f,%.3ff,0.0f],left_rotation:[0.0f,0.0f,0.0f,1.0f],"
						+ "scale:[%.3ff,%.3ff,%.3ff],right_rotation:[0.0f,0.0f,0.0f,1.0f]}}",
				boss.getX(), boss.getY(), boss.getZ(), modelTag, ownerTag, marker, model, seed / 2.0f, seed, seed, seed);
		MinecraftServer server = level.getServer();
		// run from inside another command (an admin's /hellcraft lucifer summon) the summon is queued until
		// that command finishes, so the display is looked up on the following ticks instead of right here;
		// run in the boss's own dimension (the source defaults to the overworld)
		server.getCommands().performPrefixedCommand(server.createCommandSourceStack().withLevel(level), command);
		pending.put(boss.getUUID(), new Pending(model, marker, command, 0));
		yaws.put(boss.getUUID(), boss.getYRot());
		anims.put(boss.getUUID(), new Anim(scale));
	}

	private record Pending(String model, String marker, String command, int ticks) {
	}

	/** Finds displays whose summon has run since attach(); gives up (and unhides the boss) after 2 s. */
	private void resolvePending() {
		pending.entrySet().removeIf(entry -> {
			Entity boss = level.getEntity(entry.getKey());
			Pending p = entry.getValue();
			if (boss == null || !boss.isAlive()) {
				return true;
			}
			List<Entity> found = level.getEntitiesOfClass(Entity.class, boss.getBoundingBox().inflate(8),
					e -> e.entityTags().contains(p.marker()));
			if (!found.isEmpty()) {
				HellcraftMod.LOGGER.info("Boss model attached: {}", p.model());
				displays.put(entry.getKey(), found.getFirst().getUUID());
				return true;
			}
			if (p.ticks() >= 40) {
				HellcraftMod.LOGGER.warn("Could not attach the {} model; the boss keeps its vanilla look. Command: {}", p.model(), p.command());
				boss.setInvisible(false);
				return true;
			}
			entry.setValue(new Pending(p.model(), p.marker(), p.command(), p.ticks() + 1));
			return false;
		});
	}

	// ------------------------------------------------------------------ what the fights ask for

	/** Plays a pose on a boss's model (a roar asked for while it is still rising plays once it has risen). */
	public void pose(@Nullable Entity boss, Pose pose) {
		Anim a = boss == null ? null : anims.get(boss.getUUID());
		if (a == null || a.dying >= 0) {
			return;
		}
		if (a.spawn > 0) {
			a.queued = pose;
			return;
		}
		a.pose = pose;
		a.poseTick = 0;
		// a blow lands at once; the rest ease in on the next update
		if (pose == Pose.STRIKE || pose == Pose.SLAM) {
			Entity display = display(boss.getUUID());
			if (display != null) {
				apply(display, a, 2);
			}
		}
	}

	/** The boss was hurt: its model shudders and flashes red. */
	public void hurt(@Nullable Entity boss) {
		Anim a = boss == null ? null : anims.get(boss.getUUID());
		if (a == null || a.dying >= 0) {
			return;
		}
		boolean fresh = a.hurt <= 0;
		a.hurt = HURT_TICKS;
		Entity display = display(boss.getUUID());
		if (fresh && display instanceof Display d) {
			((DisplayAccess) d).hellcraft$setGlowColorOverride(HURT_GLOW);
			d.setGlowingTag(true);
		}
	}

	@Nullable
	private Entity display(UUID bossId) {
		UUID id = displays.get(bossId);
		return id == null ? null : level.getEntity(id);
	}

	// ------------------------------------------------------------------ every tick

	/** Keeps every model on its boss, turned toward the nearest of the given players, and animated. */
	public void tick(List<ServerPlayer> watchers) {
		resolvePending();
		displays.entrySet().removeIf(entry -> {
			Entity display = level.getEntity(entry.getValue());
			Entity boss = level.getEntity(entry.getKey());
			if (boss == null) {
				// unloaded (the fight waits for it) or already gone (cleanup removes the display)
				return false;
			}
			if (!boss.isAlive()) {
				fall(entry.getKey(), display);
				yaws.remove(entry.getKey());
				return true;
			}
			if (display == null) {
				return false;
			}
			float yaw = turnToward(entry.getKey(), boss, nearest(boss, watchers));
			display.snapTo(boss.getX(), boss.getY(), boss.getZ(), yaw + HellConfig.get().luciferModelYawOffset, 0.0f);
			Anim a = anims.get(entry.getKey());
			if (a != null) {
				animate(display, boss, a);
			}
			return false;
		});
	}

	/** One tick of a living boss's animation. */
	private static void animate(Entity display, Entity boss, Anim a) {
		a.age++;
		Vec3 here = boss.position();
		if (a.last != null) {
			double speed = Math.sqrt(Math.pow(here.x - a.last.x, 2) + Math.pow(here.z - a.last.z, 2));
			// eased, so a step here and there doesn't make it twitch
			a.moving += ((float) Math.min(1.0, speed / 0.15) - a.moving) * 0.25f;
		}
		a.last = here;
		if (a.spawn > 0) {
			if (a.spawn == SPAWN_TICKS) {
				// grow out of the ground in one smooth interpolation
				apply(display, a, SPAWN_TICKS);
			}
			if (--a.spawn == 0 && a.queued != null) {
				a.pose = a.queued;
				a.poseTick = 0;
				a.queued = null;
			}
			return;
		}
		if (a.pose != Pose.IDLE && ++a.poseTick >= a.pose.length) {
			a.pose = Pose.IDLE;
			a.poseTick = 0;
		}
		if (a.hurt > 0 && --a.hurt == 0 && display instanceof Display d) {
			d.setGlowingTag(false);
		}
		if (a.age % 2 == 0) {
			apply(display, a, 3);
		}
	}

	/** A dead boss's model falls over and sinks, then goes (handed to the static ticker, so the fight can end). */
	private void fall(UUID bossId, @Nullable Entity display) {
		Anim a = anims.remove(bossId);
		if (display == null) {
			return;
		}
		if (a == null) {
			display.discard();
			return;
		}
		display.removeTag(modelTag);
		display.removeTag(ownerTag);
		display.addTag(DYING_TAG);
		if (display instanceof Display d) {
			((DisplayAccess) d).hellcraft$setGlowColorOverride(HURT_GLOW);
			d.setGlowingTag(false);
		}
		a.spawn = 0;
		a.pose = Pose.IDLE;
		a.dying = 0;
		FALLING.add(new Falling(level, display.getUUID(), a));
	}

	/** Sends the model's pose for this moment, for the client to ease into over {@code ticks}. */
	private static void apply(Entity display, Anim a, int ticks) {
		if (!(display instanceof Display d)) {
			return;
		}
		DisplayAccess access = (DisplayAccess) d;
		access.hellcraft$setTransformation(transformation(a));
		access.hellcraft$setInterpolationDuration(ticks);
		access.hellcraft$setInterpolationDelay(0);
	}

	/** The model's transformation for its state now. */
	static Transformation transformation(Anim a) {
		float s = a.scale;
		float t = a.age;
		float lean = 0;      // degrees about X: + tips the head forward
		float roll = 0;      // degrees about Z
		float forward = 0;   // blocks toward the front
		float lift = 0;      // blocks up
		float k = 1;         // overall size
		float ky = 1;        // extra height (squash and stretch)
		float kxz = 1;       // extra girth

		if (a.spawn == SPAWN_TICKS) {
			// the end of the rise: full size, standing
			return compose(s, 0, 0, 0, 0, 1, 1, 1);
		}
		if (a.dying >= 0) {
			float p = Math.min(1, a.dying / (float) DEATH_TICKS);
			roll = 82 * p * p;
			lean = 10 * p;
			lift = -0.3f * s * p;
			k = 1 - 0.3f * p;
			return compose(s, lean, roll, forward, lift, k, ky, kxz);
		}
		// breathing
		float breathe = 0.03f * (float) Math.sin(t * 0.12);
		ky += breathe;
		kxz -= breathe * 0.5f;
		// walking: a bob with each step, a forward lean and a waddle
		float step = (float) Math.sin(t * 0.45);
		lift += 0.07f * s * Math.abs(step) * a.moving;
		lean += 7 * a.moving;
		roll += 3 * step * a.moving;

		float p = a.pose.length == 0 ? 0 : Math.min(1, a.poseTick / (float) a.pose.length);
		switch (a.pose) {
			case WINDUP -> {
				float e = 1 - (1 - p) * (1 - p);
				lean -= 16 * e;
				k *= 1 + 0.08f * e;
				lift += 0.06f * s * e;
			}
			case STRIKE -> {
				float q = 1 - p;
				lean += 28 * q;
				forward += 0.4f * s * q;
				k *= 1 + 0.04f * q;
			}
			case SLAM -> {
				float q = (float) Math.sin(p * Math.PI);
				ky *= 1 - 0.22f * q;
				kxz *= 1 + 0.15f * q;
			}
			case ROAR -> {
				float q = (float) Math.sin(p * Math.PI);
				k *= 1 + 0.14f * q;
				lean -= 10 * q;
				roll += 5 * (float) Math.sin(t * 1.9) * q;
			}
			case IDLE -> {
			}
		}
		if (a.hurt > 0) {
			float h = a.hurt / (float) HURT_TICKS;
			roll += (a.hurt % 2 == 0 ? 6 : -6) * h;
			k *= 1 + 0.03f * h;
		}
		return compose(s, lean, roll, forward, lift, k, ky, kxz);
	}

	private static Transformation compose(float s, float lean, float roll, float forward, float lift, float k, float ky, float kxz) {
		float sy = s * k * ky;
		float sxz = s * k * kxz;
		// the item model is centred on the entity: lift it by half its height so the feet stand on the ground
		Vector3f translation = new Vector3f(0, sy / 2 + lift, forward);
		Quaternionf rotation = new Quaternionf().rotationX((float) Math.toRadians(lean)).rotateZ((float) Math.toRadians(roll));
		return new Transformation(translation, rotation, new Vector3f(sxz, sy, sxz), new Quaternionf());
	}

	// ------------------------------------------------------------------ facing

	@Nullable
	private static ServerPlayer nearest(Entity boss, List<ServerPlayer> watchers) {
		ServerPlayer best = null;
		double bestDist = Double.MAX_VALUE;
		for (ServerPlayer p : watchers) {
			double d = p.distanceToSqr(boss);
			if (d < bestDist && !p.isSpectator()) {
				bestDist = d;
				best = p;
			}
		}
		return best;
	}

	private float turnToward(UUID bossId, Entity boss, @Nullable ServerPlayer target) {
		float current = yaws.getOrDefault(bossId, boss.getYRot());
		if (target == null) {
			return current;
		}
		// Minecraft yaw: 0 faces +Z (south), 90 faces -X (west)
		float wanted = (float) Math.toDegrees(Math.atan2(-(target.getX() - boss.getX()), target.getZ() - boss.getZ()))
				+ faceTurns.getOrDefault(bossId, 0.0f);
		float delta = wrap(wanted - current);
		float next = current + Math.max(-MAX_TURN, Math.min(MAX_TURN, delta));
		yaws.put(bossId, next);
		boss.setYRot(next);
		return next;
	}

	private static float wrap(float degrees) {
		float d = degrees % 360.0f;
		if (d >= 180.0f) {
			d -= 360.0f;
		}
		if (d < -180.0f) {
			d += 360.0f;
		}
		return d;
	}

	/**
	 * Turns a side of the model toward the target instead of its front: the Emperor's pale yellow face is
	 * on the model's east side (-90), the black one on its west side (+90). The turn is animated by tick().
	 */
	public void showFace(UUID bossId, float turn) {
		faceTurns.put(bossId, turn);
	}

	public boolean owns(UUID id) {
		if (displays.containsValue(id)) {
			return true;
		}
		// a display whose summon ran but that tick() has not picked up yet (anything else is a leftover)
		Entity e = level.getEntity(id);
		if (e == null) {
			return false;
		}
		for (Pending p : pending.values()) {
			if (e.entityTags().contains(p.marker())) {
				return true;
			}
		}
		return false;
	}

	/** Removes every model (the bosses themselves are handled by the fight); a dead boss's model still falls. */
	public void clear() {
		for (Map.Entry<UUID, UUID> entry : displays.entrySet()) {
			Entity display = level.getEntity(entry.getValue());
			Entity boss = level.getEntity(entry.getKey());
			if (boss instanceof LivingEntity body && body.isDeadOrDying()) {
				fall(entry.getKey(), display);
			} else if (display != null) {
				display.discard();
			}
		}
		displays.clear();
		yaws.clear();
		faceTurns.clear();
		pending.clear();
		anims.clear();
		// displays summoned after their boss was gone, or never picked up
		for (Entity e : level.getEntitiesOfClass(Entity.class, AABB.ofSize(home, 200, 400, 200), d -> d.entityTags().contains(modelTag))) {
			e.discard();
		}
	}

	/** Headless self-test for the smoke test: the model stands on its feet, lunges forward and topples sideways. */
	public static String selfTest() {
		Anim a = new Anim(2.0f);
		a.spawn = 0;
		Transformation idle = transformation(a);
		a.pose = Pose.STRIKE;
		a.poseTick = 0;
		Transformation strike = transformation(a);
		a.pose = Pose.IDLE;
		a.dying = DEATH_TICKS;
		Transformation dead = transformation(a);
		boolean feet = Math.abs(idle.translation().y() - idle.scale().y() / 2) < 1.0e-3;
		boolean lunges = strike.translation().z() > 0.5f;
		boolean topples = Math.abs(dead.leftRotation().z()) > 0.5f;
		return String.format(Locale.ROOT, "Boss animation test: feet=%s lunge=%s topple=%s", feet, lunges, topples);
	}
}
