package net.thesmallthings.hellcraft.hazard.lucifer;

import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import net.thesmallthings.hellcraft.HellcraftMod;
import net.thesmallthings.hellcraft.config.HellConfig;
import org.jetbrains.annotations.Nullable;

import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

/**
 * Lucifer's own look. The real boss (a wither skeleton, later a wither) is made invisible and an
 * item_display entity showing a model from the Hellcraft resource pack follows it every tick, turning
 * to face whoever he is fighting. The models are in assets/hellcraft/models/item/lucifer_*.json
 * (generated by tools/gen_models.py): 2 blocks tall, feet at the bottom, face toward -Z.
 */
final class LuciferModel {
	static final String TAG = "hellcraft_lucifer_model";
	private static final float MODEL_HEIGHT = 2.0f;
	private static final float MAX_TURN = 12.0f;

	private final ServerLevel level;
	/** boss UUID -> display UUID */
	private final Map<UUID, UUID> displays = new HashMap<>();
	private final Map<UUID, Float> yaws = new HashMap<>();
	/** boss UUID -> extra turn (degrees) so that another side of the model faces the target */
	private final Map<UUID, Float> faceTurns = new HashMap<>();
	/** boss UUID -> a display that was summoned but not found yet */
	private final Map<UUID, Pending> pending = new HashMap<>();

	LuciferModel(ServerLevel level) {
		this.level = level;
	}

	/** Hides the boss and gives it the named model, scaled so its height matches `height` blocks. */
	void attach(LivingEntity boss, String model, float height) {
		if (!HellConfig.get().luciferModels) {
			return;
		}
		boss.setInvisible(true);
		if (boss instanceof Mob mob) {
			// held items and armour would float around the invisible body
			for (EquipmentSlot slot : EquipmentSlot.values()) {
				mob.setItemSlot(slot, ItemStack.EMPTY);
			}
		}
		float scale = height / MODEL_HEIGHT;
		String marker = "hellcraft_model_" + boss.getUUID();
		// the item model is centred on the entity: lift it by half its size so the feet stand on the ground
		String command = String.format(Locale.ROOT,
				"summon minecraft:item_display %.3f %.3f %.3f {Tags:[\"%s\",\"%s\",\"%s\"],"
						+ "item:{id:\"minecraft:stick\",count:1,components:{\"minecraft:item_model\":\"hellcraft:%s\"}},"
						+ "item_display:\"none\",billboard:\"fixed\",teleport_duration:2,view_range:4.0f,brightness:{sky:15,block:12},"
						+ "transformation:{translation:[0.0f,%.3ff,0.0f],left_rotation:[0.0f,0.0f,0.0f,1.0f],"
						+ "scale:[%.3ff,%.3ff,%.3ff],right_rotation:[0.0f,0.0f,0.0f,1.0f]}}",
				boss.getX(), boss.getY(), boss.getZ(), TAG, LuciferManager.TAG, marker, model, scale / 2.0f, scale, scale, scale);
		MinecraftServer server = level.getServer();
		// run from inside another command (an admin's /hellcraft lucifer start) the summon is queued until
		// that command finishes, so the display is looked up on the following ticks instead of right here
		server.getCommands().performPrefixedCommand(server.createCommandSourceStack(), command);
		pending.put(boss.getUUID(), new Pending(model, marker, command, 0));
		yaws.put(boss.getUUID(), boss.getYRot());
	}

	private record Pending(String model, String marker, String command, int ticks) {
	}

	/** Finds displays whose summon has run since attach(); gives up (and unhides the boss) after 2 s. */
	private void resolvePending() {
		pending.entrySet().removeIf(entry -> {
			Entity boss = level.getEntity(entry.getKey());
			Pending p = entry.getValue();
			if (boss == null || !boss.isAlive()) {
				return true;
			}
			List<Entity> found = level.getEntitiesOfClass(Entity.class, boss.getBoundingBox().inflate(8),
					e -> e.entityTags().contains(p.marker()));
			if (!found.isEmpty()) {
				HellcraftMod.LOGGER.info("Lucifer model: {}", p.model());
				displays.put(entry.getKey(), found.getFirst().getUUID());
				return true;
			}
			if (p.ticks() >= 40) {
				HellcraftMod.LOGGER.warn("Could not give Lucifer his {} model; he keeps his vanilla look. Command: {}", p.model(), p.command());
				boss.setInvisible(false);
				return true;
			}
			entry.setValue(new Pending(p.model(), p.marker(), p.command(), p.ticks() + 1));
			return false;
		});
	}

	/** Keeps every model on its boss, turned toward the nearest of the given players. */
	void tick(List<ServerPlayer> watchers) {
		resolvePending();
		displays.entrySet().removeIf(entry -> {
			Entity display = level.getEntity(entry.getValue());
			Entity boss = level.getEntity(entry.getKey());
			if (boss == null) {
				// unloaded (the fight waits for it) or already gone (cleanup removes the display)
				return false;
			}
			if (!boss.isAlive()) {
				if (display != null) {
					display.discard();
				}
				yaws.remove(entry.getKey());
				return true;
			}
			if (display == null) {
				return false;
			}
			float yaw = turnToward(entry.getKey(), boss, nearest(boss, watchers));
			display.snapTo(boss.getX(), boss.getY(), boss.getZ(), yaw + HellConfig.get().luciferModelYawOffset, 0.0f);
			return false;
		});
	}

	@Nullable
	private static ServerPlayer nearest(Entity boss, List<ServerPlayer> watchers) {
		ServerPlayer best = null;
		double bestDist = Double.MAX_VALUE;
		for (ServerPlayer p : watchers) {
			double d = p.distanceToSqr(boss);
			if (d < bestDist && !p.isSpectator()) {
				bestDist = d;
				best = p;
			}
		}
		return best;
	}

	private float turnToward(UUID bossId, Entity boss, @Nullable ServerPlayer target) {
		float current = yaws.getOrDefault(bossId, boss.getYRot());
		if (target == null) {
			return current;
		}
		// Minecraft yaw: 0 faces +Z (south), 90 faces -X (west)
		float wanted = (float) Math.toDegrees(Math.atan2(-(target.getX() - boss.getX()), target.getZ() - boss.getZ()))
				+ faceTurns.getOrDefault(bossId, 0.0f);
		float delta = wrap(wanted - current);
		float next = current + Math.max(-MAX_TURN, Math.min(MAX_TURN, delta));
		yaws.put(bossId, next);
		boss.setYRot(next);
		return next;
	}

	private static float wrap(float degrees) {
		float d = degrees % 360.0f;
		if (d >= 180.0f) {
			d -= 360.0f;
		}
		if (d < -180.0f) {
			d += 360.0f;
		}
		return d;
	}

	/**
	 * Turns a side of the model toward the target instead of its front: the Emperor's pale yellow face is
	 * on the model's east side (-90), the black one on its west side (+90). The turn is animated by tick().
	 */
	void showFace(UUID bossId, float turn) {
		faceTurns.put(bossId, turn);
	}

	boolean owns(UUID id) {
		if (displays.containsValue(id)) {
			return true;
		}
		// a display whose summon ran but that tick() has not picked up yet
		Entity e = level.getEntity(id);
		return e != null && e.entityTags().contains(TAG);
	}

	/** Removes every model (the bosses themselves are handled by the fight). */
	void clear() {
		for (UUID id : displays.values()) {
			Entity display = level.getEntity(id);
			if (display != null) {
				display.discard();
			}
		}
		displays.clear();
		yaws.clear();
		faceTurns.clear();
		pending.clear();
		// displays summoned after their boss was gone, or never picked up
		for (Entity e : level.getEntitiesOfClass(Entity.class, AABB.ofSize(Vec3.ZERO, 200, 400, 200), d -> d.entityTags().contains(TAG))) {
			e.discard();
		}
	}
}
